repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
        exclude: ^tests/layouts/
      - id: check-toml
        exclude: ^cookiecutter/
      - id: check-json
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
        args: ["--fix=lf"]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.3
    hooks:
      # Run the linter.
      - id: ruff-check
        exclude: ^cookiecutter/
      # Run the formatter.
      - id: ruff-format
        exclude: ^cookiecutter/
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy
        name: mypy (library code)
        exclude: ^cookiecutter/
        # exclude: "^(docs/)"
        additional_dependencies:
          - docutils-stubs
          - pillow
          - types-requests
          - types-PyYAML
          - pydantic>=2.4
  - repo: https://github.com/streetsidesoftware/cspell-cli
    rev: v9.2.1
    hooks:
      - id: cspell # Spell check changed files
        exclude: '.*\.svg$'
