name: Docs

on:
  push:
    branches: [main]
    paths:
      - "**/*.py"
      - "!cookiecutter/**"
      - "src/sphinx_social_cards/**/*.yml"
      - "docs/**"
      - ".pre-commit-config.yaml"
      - "uv.lock"
      - "pyproject.toml"
      - ".github/workflows/docs.yml"
  pull_request:
    branches: [main]
    paths:
      - "**/*.py"
      - "!cookiecutter/**"
      - "src/sphinx_social_cards/**/*.yml"
      - "docs/**"
      - ".pre-commit-config.yaml"
      - "uv.lock"
      - "pyproject.toml"
      - ".github/workflows/docs.yml"
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
    permissions:
      contents: read
    env:
      SPHINX_IMMATERIAL_EXTERNAL_RESOURCE_CACHE_DIR: ${{ github.workspace }}/docs_theme_build_cache
    steps:
      - if: runner.os == 'Linux'
        run: |-
          sudo apt-get update
          sudo apt-get install -y libgl-dev libglvnd-dev libxkbcommon-x11-0
          echo "QT_QPA_PLATFORM=offscreen" >> "${GITHUB_ENV}"
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Setup Python
        uses: actions/setup-python@v6
        id: python-setup
        with:
          python-version: "3.x"
      - name: Setup uv
        uses: astral-sh/setup-uv@d0cc045d04ccac9d8b7881df0226f9e82c39688e # v6.8.0
        with:
          python-version: ${{ steps.python-setup.outputs.python-version }}
          enable-cache: true
      - name: Restore cache of sphinx-immaterial fonts
        uses: actions/cache/restore@v4
        id: restore-cache
        with:
          path: ${{ env.SPHINX_IMMATERIAL_EXTERNAL_RESOURCE_CACHE_DIR }}
          key: ${{ matrix.os }}-docs-cache-${{ github.run_id }}
      - name: Build docs
        run: uvx nox -s docs
        env:
          GITHUB_REST_API_TOKEN: ${{ github.token }}
          FORCE_COLOR: 1
      - name: Upload docs artifact
        if: runner.os == 'Linux'
        uses: actions/upload-pages-artifact@v4
        with:
          path: docs/_build/html
      - name: Cache sphinx-immaterial fonts
        if: always() && steps.restore-cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: ${{ env.SPHINX_IMMATERIAL_EXTERNAL_RESOURCE_CACHE_DIR }}
          key: ${{ matrix.os }}-docs-cache-${{ github.run_id }}

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      # to deploy to Pages
      pages: write
      # to verify the deployment originates from an appropriate source
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        id: deployment
