name: Release

on:
  push:
    tags:
      - 'v*'
    branches: [main]
  pull_request:
    branches: [main]

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          # Need full history to determine version number.
          fetch-depth: 0
          persist-credentials: false
      - name: Build distributions
        run: pipx run build
      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/*

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      # needed for trusted publishing to PyPI
      id-token: write
    steps:
      - name: Download distributions
        uses: actions/download-artifact@v5
        with:
          name: dist
          path: dist
      - name: Check Distributions
        if: github.ref != 'refs/heads/main' && !startsWith(github.ref, 'refs/tags/v')
        run: pipx run twine check dist/*
      - name: Publish to PyPI
        if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')
        uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e # v1.13.0
        with:
          # Publish to Test PyPI if not a tagged commit on main branch.
          repository-url: ${{ startsWith(github.ref, 'refs/tags/v') && 'https://upload.pypi.org/legacy/' || 'https://test.pypi.org/legacy/' }}
